"""Daily market news brief — runs each morning before the entry pipelines.

Fetches recent headlines for broad-market ETFs (SPY, QQQ, IWM, DIA) via
Alpaca News + a couple of UK proxies via yfinance, then asks Claude to
distill them into 3-5 themes that summarize the day's market context.
Output goes to state/daily_news/YYYY-MM-DD.md and is read by LLM
strategies that opt into the `get_daily_news_brief` tool.

Cheap to run (single Haiku call, no per-ticker tools), so we trigger it
~30 min before UK-EU entry to give the file plenty of time to land.
"""
from __future__ import annotations

import logging
import os
from datetime import date, datetime, timezone
from pathlib import Path

from trading_bot.llm.claude_code import ClaudeCodeError, run_claude
from trading_bot.state.paths import STATE_ROOT
from trading_bot.tools.news import get_recent_news


log = logging.getLogger(__name__)


_BROAD_TICKERS = ["SPY", "QQQ", "IWM", "DIA"]  # US broad market
_UK_PROXIES = ["VOD.L", "BP.L", "HSBA.L"]      # high-volume UK names for yfinance fallback


def run_daily_news_brief(today: date) -> dict:
    """Fetch headlines, ask Claude for a themed brief, write to state/."""
    if not os.environ.get("CLAUDE_CODE_OAUTH_TOKEN"):
        log.error("CLAUDE_CODE_OAUTH_TOKEN not set — skipping daily news brief")
        return {"skipped": True, "reason": "no oauth token"}

    headlines = _gather_headlines()
    if not headlines:
        log.warning("No headlines fetched for %s; skipping brief", today.isoformat())
        return {"skipped": True, "reason": "no headlines"}

    log.info("daily-news-brief: %d headlines gathered for %s", len(headlines), today.isoformat())
    prompt = _build_prompt(today, headlines)
    try:
        result = run_claude(prompt, model="haiku")
    except ClaudeCodeError as e:
        log.error("daily-news-brief: Claude call failed: %s", e)
        return {"error": str(e)}

    brief_md = result.text.strip()
    if not brief_md:
        return {"error": "empty response"}

    path = _brief_path(today)
    path.parent.mkdir(parents=True, exist_ok=True)
    header = (
        f"# Daily market news brief — {today.isoformat()}\n\n"
        f"*Auto-generated by the daily-news-brief agent on "
        f"{datetime.now(timezone.utc).isoformat()}. Read by LLM strategies "
        f"as today's market-wide context.*\n\n---\n\n"
    )
    path.write_text(header + brief_md + "\n")
    log.info("daily-news-brief: wrote %s", path)
    return {
        "date": today.isoformat(),
        "headlines_in": len(headlines),
        "path": str(path),
        "cost_usd": result.total_cost_usd,
    }


def _gather_headlines() -> list[dict]:
    """Pull broad-market headlines from Alpaca News + UK proxies. Returns
    a flat list of {timestamp, headline, summary, tickers} dicts."""
    seen_urls: set[str] = set()
    out: list[dict] = []
    try:
        by_ticker = get_recent_news(_BROAD_TICKERS + _UK_PROXIES, days=1, limit=30)
    except Exception as e:
        log.warning("News fetch failed during brief: %s", e)
        return out
    for items in by_ticker.values():
        for item in items:
            if item.url and item.url in seen_urls:
                continue
            if item.url:
                seen_urls.add(item.url)
            out.append({
                "timestamp": item.timestamp,
                "headline": item.headline,
                "summary": (item.summary or "")[:240],
                "tickers": list(item.tickers),
            })
    # Most recent first
    out.sort(key=lambda x: x.get("timestamp", ""), reverse=True)
    return out[:40]


def _build_prompt(today: date, headlines: list[dict]) -> str:
    bullets = "\n".join(
        f"- [{h.get('timestamp', '')[:10]}] {h.get('headline', '')}"
        + (f" — {h['summary']}" if h.get('summary') else "")
        for h in headlines
    )
    return f"""You are the daily market news briefer for an algorithmic trading bot.
Today is {today.isoformat()}. Below are ~{len(headlines)} headlines from the
last 24 hours covering broad US + UK market context.

Your job: distill these into a short markdown brief that downstream LLM
strategies will use as today's macro/news context. Be concise. Themes >
individual headlines.

## Headlines

{bullets}

## Output

Write a markdown brief with these sections:

### Themes (3-5)
A bulleted list. For each theme: 1 line on what's moving and 1 line on
which sectors / asset types it likely affects. No prose preamble.

### Risk tone
One line: are markets risk-on, risk-off, or mixed today? Cite the most
relevant headline that drives this read.

### Sectors flagged
A short bulleted list of sectors with a directional lean (bullish /
bearish / watching) based on today's news. Skip sectors without news.

Be terse. The bot reads this verbatim; padding wastes tokens.
"""


def _brief_path(d: date) -> Path:
    return STATE_ROOT / "daily_news" / f"{d.isoformat()}.md"
